from aws_cdk import Duration, RemovalPolicy, Stack
from aws_cdk import aws_ec2 as ec2
from aws_cdk import aws_rds as rds
from aws_cdk import aws_secretsmanager as secretsmanager
from aws_cdk import aws_ssm as ssm
from constructs import Construct


class DatabaseStack(Stack):
    def __init__(self, scope: Construct, construct_id: str, **kwargs: object) -> None:
        super().__init__(scope, construct_id, **kwargs)

        # VPC moved here from ComputeStack.
        # nat_gateways=0 → CDK creates PUBLIC + PRIVATE_ISOLATED subnets (no NAT cost).
        self.vpc = ec2.Vpc(
            self,
            "GradingVpc",
            max_azs=2,
            nat_gateways=0,
        )

        # All three SGs live here so every cross-SG rule is intra-stack.
        # ComputeStack passes the pre-wired SGs to the ALB and FargateService
        # via Fn::ImportValue references — no new dependency direction is created.
        self.alb_sg = ec2.SecurityGroup(
            self,
            "AlbSg",
            vpc=self.vpc,
            description="Allow HTTP 80 from internet",
            allow_all_outbound=True,
        )
        self.alb_sg.add_ingress_rule(ec2.Peer.any_ipv4(), ec2.Port.tcp(80))

        self.fargate_sg = ec2.SecurityGroup(
            self,
            "FargateSg",
            vpc=self.vpc,
            description="Allow port 8000 from ALB only",
            allow_all_outbound=True,
        )
        self.fargate_sg.add_ingress_rule(self.alb_sg, ec2.Port.tcp(8000))

        self.rds_sg = ec2.SecurityGroup(
            self,
            "RdsSg",
            vpc=self.vpc,
            description="PostgreSQL access from Fargate tasks",
            allow_all_outbound=False,
        )
        self.rds_sg.add_ingress_rule(self.fargate_sg, ec2.Port.tcp(5432))

        # DB credentials — password generated by Secrets Manager, never hardcoded.
        self.db_secret = secretsmanager.Secret(
            self,
            "DbSecret",
            description="RDS PostgreSQL credentials for grading-app",
            generate_secret_string=secretsmanager.SecretStringGenerator(
                secret_string_template='{"username": "grading_app"}',
                generate_string_key="password",
                exclude_punctuation=True,
                password_length=32,
            ),
        )

        # RDS PostgreSQL 16 — free-tier sizing (db.t3.micro, 20 GB, Single-AZ)
        self.db_instance = rds.DatabaseInstance(
            self,
            "GradingDb",
            engine=rds.DatabaseInstanceEngine.postgres(
                version=rds.PostgresEngineVersion.VER_16
            ),
            instance_type=ec2.InstanceType.of(
                ec2.InstanceClass.T3, ec2.InstanceSize.MICRO
            ),
            credentials=rds.Credentials.from_secret(self.db_secret),
            vpc=self.vpc,
            vpc_subnets=ec2.SubnetSelection(
                subnet_type=ec2.SubnetType.PRIVATE_ISOLATED
            ),
            multi_az=False,
            allocated_storage=20,
            storage_encrypted=True,
            deletion_protection=False,
            removal_policy=RemovalPolicy.DESTROY,
            backup_retention=Duration.days(0),
            publicly_accessible=False,
            security_groups=[self.rds_sg],
            database_name="grading",
        )

        ssm.StringParameter(
            self,
            "DbSecretArnParam",
            parameter_name="/grading/database/secret-arn",
            string_value=self.db_secret.secret_arn,
        )

        ssm.StringParameter(
            self,
            "DbEndpointParam",
            parameter_name="/grading/database/endpoint",
            string_value=self.db_instance.db_instance_endpoint_address,
        )
